version: "3.3"
services:
  slideshow-data:
    image: jimareed/slideshow-data:latest
    container_name: slideshow-data
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - SLIDESHOW_API_ID=-- insert here --
      - SLIDESHOW_DOMAIN=-- insert here --
      
networks:
    default: